services:
  postgres:
    image: postgres
    container_name: postgres1-credit-analysis
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5430:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080