openapi: 3.0.0
info:
  title: Credit Analysis API
  description: API for credit analysis
  version: 1.0.0
servers:
  - url: http://localhost:8081
tags:
  - name: credit analysis
paths:
  /credit/analysis:
    post:
      summary: Credit Analysis Endpoint
      tags:
        - credit analysis
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                clientId:
                  type: string
                  format: uuid
                  description: Client ID
                monthlyIncome:
                  type: number
                  format: float
                  description: Monthly income
                requestedAmount:
                  type: number
                  format: float
                  description: Requested loan amount
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    description: Analysis ID
                  approved:
                    type: boolean
                    description: Indicates if the loan was approved or not
                  approvedLimit:
                    type: number
                    format: float
                    description: Approved loan limit
                  withdraw:
                    type: number
                    format: float
                    description: Indicates the loan amount to withdrawn
                  annualInterest:
                    type: number
                    format: float
                    description: Annual interest rate for the loan in percentage
                  clientId:
                    type: string
                    format: uuid
                  date:
                    type: string
                    format: date-time
    get:
      summary: Get all Analysis
      tags:
        - credit analysis
      description: Client ID or CPF can be provided as query parameters in order to return all the credit analysis for a specific client
      parameters:
        - name: clientId
          in: query
          description: Client ID
          schema:
            type: string
            format: uuid
        - name: cpf
          in: query
          description: Client CPF
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: string
                      description: Analysis ID
                    approved:
                      type: boolean
                      description: Indicates if the loan was approved or not
                    approvedLimit:
                      type: number
                      format: float
                      description: Approved loan limit
                    requestedAmount:
                      type: number
                      format: float
                      description: Requested loan amount
                    withdraw:
                      type: boolean
                      description: Indicates if the loan amount was withdrawn
                    annualInterest:
                      type: number
                      format: float
                      description: Annual interest rate for the loan in percentage
                    clientId:
                      type: string
                      format: uuid
                    date:
                      type: string
                      format: date-time
        '404':
          description: Analysis not found
