openapi: 3.0.0
info:
  title: Credit Analysis API
  description: API for credit analysis
  version: 1.0.1
servers:
  - url: http://localhost:9001
tags:
  - name: credit analysis
paths:
  /credit/analysis:
    post:
      summary: Credit Analysis Endpoint
      tags:
        - credit analysis
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                clientId:
                  type: integer
                  description: Client ID
                monthlyIncome:
                  type: number
                  format: float
                  description: Monthly income
                requestedAmount:
                  type: number
                  format: float
                  description: Requested loan amount
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Analysis ID
                  approved:
                    type: boolean
                    description: Indicates if the loan was approved or not
                  approvedLimit:
                    type: number
                    format: float
                    description: Approved loan limit
                  withdraw:
                    type: number
                    example: 1000
                    description: Indicates amount was withdrawn
                  annualInterest:
                    type: number
                    format: float
                    description: Annual interest rate for the loan in percentage
                  clientId:
                    type: string
                    format: uuid
                  date:
                    type: string
                    format: date-time
    get:
      summary: Get all Analysis
      tags:
        - credit analysis
      parameters:
        - name: cpf
          in: query
          description: client CPF
          required: false
          schema:
            type: string
        - name: clientId
          in: query
          description: client id
          required: false
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      description: Analysis ID
                    approved:
                      type: boolean
                      description: Indicates if the loan was approved or not
                    approvedLimit:
                      type: number
                      format: float
                      description: Approved loan limit
                    requestedAmount:
                      type: number
                      format: float
                      description: Requested loan amount
                    withdraw:
                      type: number
                      example: 1000
                      description: Indicates amount was withdrawn
                    annualInterest:
                      type: number
                      format: float
                      description: Annual interest rate for the loan in percentage
                    clientId:
                      type: string
                      format: uuid
                    date:
                      type: string
                      format: date-time
        '404':
          description: Analysis not found
  /credit/analysis/{id}:
    get:
      summary: Get Analysis by ID Endpoint
      tags:
        - credit analysis
      parameters:
        - name: id
          in: path
          description: Analysis ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Analysis ID
                  approved:
                    type: boolean
                    description: Indicates if the loan was approved or not
                  approvedLimit:
                    type: number
                    format: float
                    description: Approved loan limit
                  requestedAmount:
                    type: number
                    format: float
                    description: Requested loan amount
                  withdraw:
                    type: number
                    example: 2000
                    description: Indicates amount was withdrawn
                  annualInterest:
                    type: number
                    format: float
                    description: Annual interest rate for the loan in percentage
                  date:
                    type: string
                    format: date-time
        '404':
          description: Analysis not found

